version: '3.5'
services:
  postgres:
    image: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
    - ./postgres/.env
    volumes:
    - postgres:/data/db
    ports:
    - "5433:5432"

volumes:
  postgres:
