version: '3.5'
services:
  postgres_demo:
    image: postgres_demo
    container_name: postgres_demo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    env_file:
    - ./postgres/.env
    volumes:
    - postgres_data:/data/db
    ports:
    - "5433:5432"

volumes:
  postgres_data:
